version: "3"
networks:
  default:
    external:
      name: dockerbox
services:
  webpack:
    image: blendmarketing/webpack
    ports:
      - 80
    environment:
      - VIRTUAL_HOST={hostname}
    volumes:
      - .:/app:rw
  styleguide:
    image: blendmarketing/webpack
    ports:
      - 6060
    environment:
      - VIRTUAL_HOST={hostname}
    volumes:
      - .:/app:rw
