version: "3"
networks:
  default:
    external:
      name: dockerbox
services:
  webpack:
    image: node.example.com
    ports:
      - 80
    environment:
      - VIRTUAL_HOST=example.com
    restart: unless-stopped
    volumes:
      - ./src:/app/src:delegated
    command: yarn start
  styleguide:
    image: node.example.com
    ports:
      - 6060
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=styleguide.example.com
      - VIRTUAL_PORT=6060
    volumes:
      - ./src:/app/src:delegated
    command: yarn styleguide
