version: "3"
networks:
  default:
    external:
      name: dockerbox
services:
  webpack:
    image: blendmarketing/webpack
    ports:
      - 80
    environment:
      - VIRTUAL_HOST=example.com
    volumes:
      - .:/app:rw
  styleguide:
    image: blendmarketing/styleguide
    ports:
      - 6060
    environment:
      - VIRTUAL_HOST=styleguide.example.com
    volumes:
      - .:/app:rw
