version: "3"
networks:
  default:
    external:
      name: dockerbox
services:
  webpack:
    build: github.com/BlendMarketing/docker-webpack
    ports:
      - 80
    environment:
      - VIRTUAL_HOST={hostname}
    volumes:
      - .:/app:rw
  styleguide:
    build: github.com/BlendMarketing/docker-styleguide
    ports:
      - 6060
    environment:
      - VIRTUAL_HOST={hostname}
    volumes:
      - .:/app:rw
