version: "3"
networks:
  default:
    external:
      name: dockerbox
services:
  webpack:
    image: webpack.{containerName}
    ports:
      - 80
    environment:
      - VIRTUAL_HOST={devDomain}
    restart: unless-stopped
    volumes:
      - ./src:/app/src:delegated
    command: yarn start
  styleguide:
    image: webpack.{containerName}
    ports:
      - 6060
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=styleguide.{devDomain}
      - VIRTUAL_PORT=6060
    volumes:
      - ./src:/app/src:delegated
    command: yarn styleguide
