FROM blendmarketing/webpack
MAINTAINER Marc Tanis "marc@blendimc.com"

COPY package.json /app/package.json
COPY yarn.lock /app/yarn.lock
COPY shim.sh /app/shim.sh
RUN cd /app && yarn shim

COPY . /app
